#!/bin/busybox sh
/bin/busybox --install -s /bin
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev
echo "Loading virtio modules..."
insmod /lib/modules/6.19.11+deb14-riscv64/virtio_mmio.ko.xz
insmod /lib/modules/6.19.11+deb14-riscv64/virtio_blk.ko.xz
insmod /lib/modules/6.19.11+deb14-riscv64/failover.ko.xz
insmod /lib/modules/6.19.11+deb14-riscv64/net_failover.ko.xz
insmod /lib/modules/6.19.11+deb14-riscv64/virtio_net.ko.xz
sleep 1
echo "Loading ext4 modules..."
insmod /lib/modules/6.19.11+deb14-riscv64/crc16.ko.xz
insmod /lib/modules/6.19.11+deb14-riscv64/mbcache.ko.xz
insmod /lib/modules/6.19.11+deb14-riscv64/jbd2.ko.xz
insmod /lib/modules/6.19.11+deb14-riscv64/ext4.ko.xz
echo "Configuring network..."
ip link set eth0 up
ip addr add 10.0.2.15/24 dev eth0
ip route add default via 10.0.2.2
echo "Mounting Alpine root..."
mount -t ext4 /dev/vda /newroot
if [ $? -eq 0 ]; then
    echo "SUCCESS! Switching to Alpine..."
    exec switch_root /newroot /bin/sh
else
    exec /bin/sh
fi
